import { useEffect, useState } from 'react';
import { Star } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

export function ReviewsSection(){
 const [rows,setRows]=useState<{id:string;customer_name:string;rating:number;review:string;service_name:string|null}[]>([]); const [name,setName]=useState(''); const [rating,setRating]=useState(5); const [review,setReview]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase.from('reviews').select('id,customer_name,rating,review,service_name').eq('is_published',true).order('created_at',{ascending:false}).limit(6).then(({data})=>setRows(data??[]));},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const {error}=await supabase.from('reviews').insert({customer_name:name.trim(),rating,review:review.trim(),is_published:false});if(error)throw error;toast.success('Thank you. Your review is awaiting approval.');setName('');setReview('');}catch(e){toast.error(e instanceof Error?e.message:'Could not submit review')}finally{setBusy(false)}}
 return <section className="border-y border-border bg-surface/30 py-20 md:py-28"><div className="mx-auto max-w-6xl px-5 md:px-8"><div className="grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">Client notes</p><h2 className="mt-4 font-display text-4xl text-ivory md:text-5xl">What our clients say.</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{rows.length?rows.map(r=><article key={r.id} className="surface-panel rounded-sm p-6"><div className="flex gap-1">{Array.from({length:5},(_,i)=><Star key={i} className={`h-4 w-4 ${i<r.rating?'fill-gold text-gold':'text-muted-foreground'}`}/>)}</div><p className="mt-4 text-sm leading-relaxed text-ivory/80">“{r.review}”</p><p className="mt-5 text-xs uppercase tracking-[.18em] text-muted-foreground">{r.customer_name}{r.service_name?` · ${r.service_name}`:''}</p></article>):<p className="text-sm text-muted-foreground">Be the first to leave a review.</p>}</div></div><form onSubmit={submit} className="surface-panel rounded-sm p-6 md:p-8"><p className="eyebrow">Share your experience</p><input required minLength={2} placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} className="mt-6 w-full rounded-sm border border-input bg-background px-3.5 py-3 text-sm text-ivory"/><div className="mt-5 flex gap-2" aria-label="Rating">{[1,2,3,4,5].map(i=><button type="button" key={i} onClick={()=>setRating(i)} aria-label={`${i} stars`}><Star className={`h-6 w-6 ${i<=rating?'fill-gold text-gold':'text-muted-foreground'}`}/></button>)}</div><textarea required minLength={10} maxLength={1000} rows={5} placeholder="Tell us about your visit" value={review} onChange={e=>setReview(e.target.value)} className="mt-5 w-full rounded-sm border border-input bg-background px-3.5 py-3 text-sm text-ivory"/><button disabled={busy} className="mt-5 w-full rounded-sm bg-gold px-5 py-3 text-xs uppercase tracking-[.2em] text-primary-foreground disabled:opacity-60">{busy?'Submitting…':'Submit review'}</button></form></div></div></section>;
}
