create table if not exists public.bookings (id uuid primary key default gen_random_uuid(),booking_code text not null unique default ('KRS-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),customer_name text not null,phone text not null,email text,service_id uuid references public.site_services(id) on delete set null,service_name text not null,appointment_date date not null,appointment_time time not null,notes text not null default '',coupon_code text,coupon_discount numeric(10,2) not null default 0,status text not null default 'pending' check(status in ('pending','confirmed','completed','cancelled','no_show')),payment_status text not null default 'unpaid' check(payment_status in ('unpaid','paid','refunded')),source text not null default 'website' check(source in ('website','whatsapp','phone','admin')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists bookings_date_idx on public.bookings(appointment_date,appointment_time); create index if not exists bookings_status_idx on public.bookings(status);
grant insert on public.bookings to anon,authenticated; grant select,update,delete on public.bookings to authenticated; grant all on public.bookings to service_role; alter table public.bookings enable row level security;
drop policy if exists "Anyone can create bookings" on public.bookings; create policy "Anyone can create bookings" on public.bookings for insert to anon,authenticated with check(length(trim(customer_name)) between 2 and 100 and length(regexp_replace(phone,'\D','','g')) between 10 and 15);
drop policy if exists "Admins can view bookings" on public.bookings; create policy "Admins can view bookings" on public.bookings for select to authenticated using(private.is_admin()); drop policy if exists "Admins can update bookings" on public.bookings; create policy "Admins can update bookings" on public.bookings for update to authenticated using(private.is_admin()) with check(private.is_admin()); drop policy if exists "Admins can delete bookings" on public.bookings; create policy "Admins can delete bookings" on public.bookings for delete to authenticated using(private.is_admin());

create table if not exists public.reviews (id uuid primary key default gen_random_uuid(),customer_name text not null,rating integer not null check(rating between 1 and 5),review text not null check(length(trim(review)) between 10 and 1000),service_name text,is_published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now()); grant insert,select on public.reviews to anon,authenticated; grant update,delete on public.reviews to authenticated; grant all on public.reviews to service_role; alter table public.reviews enable row level security;
drop policy if exists "Published reviews are public" on public.reviews; create policy "Published reviews are public" on public.reviews for select to anon,authenticated using(is_published=true); drop policy if exists "Anyone can submit reviews" on public.reviews; create policy "Anyone can submit reviews" on public.reviews for insert to anon,authenticated with check(is_published=false); drop policy if exists "Admins can update reviews" on public.reviews; create policy "Admins can update reviews" on public.reviews for update to authenticated using(private.is_admin()) with check(private.is_admin()); drop policy if exists "Admins can delete reviews" on public.reviews; create policy "Admins can delete reviews" on public.reviews for delete to authenticated using(private.is_admin());

create table if not exists public.coupons (id uuid primary key default gen_random_uuid(),code text not null unique,description text not null default '',discount_type text not null check(discount_type in ('fixed','percent')),discount_value numeric(10,2) not null check(discount_value>=0),minimum_amount numeric(10,2) not null default 0,max_uses integer,used_count integer not null default 0,starts_at timestamptz not null default now(),ends_at timestamptz,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()); grant select on public.coupons to anon,authenticated; grant insert,update,delete on public.coupons to authenticated; grant all on public.coupons to service_role; alter table public.coupons enable row level security;
drop policy if exists "Active coupons are publicly viewable" on public.coupons; create policy "Active coupons are publicly viewable" on public.coupons for select to anon,authenticated using(is_active=true and starts_at<=now() and (ends_at is null or ends_at>=now()) and (max_uses is null or used_count<max_uses)); drop policy if exists "Admins can manage coupons" on public.coupons; create policy "Admins can manage coupons" on public.coupons for all to authenticated using(private.is_admin()) with check(private.is_admin());

create table if not exists public.serviceable_pincodes (pincode text primary key check(pincode ~ '^[1-9][0-9]{5}$'),area text not null default '',is_active boolean not null default true,created_at timestamptz not null default now()); grant select on public.serviceable_pincodes to anon,authenticated; grant insert,update,delete on public.serviceable_pincodes to authenticated; grant all on public.serviceable_pincodes to service_role; alter table public.serviceable_pincodes enable row level security; drop policy if exists "Active pincodes are public" on public.serviceable_pincodes; create policy "Active pincodes are public" on public.serviceable_pincodes for select to anon,authenticated using(is_active=true); drop policy if exists "Admins manage pincodes" on public.serviceable_pincodes; create policy "Admins manage pincodes" on public.serviceable_pincodes for all to authenticated using(private.is_admin()) with check(private.is_admin()); insert into public.serviceable_pincodes(pincode,area) values('641652','Anupparpalayam Pudur / Thirumuruganpoondi') on conflict do nothing;

create table if not exists public.return_requests (id uuid primary key default gen_random_uuid(),request_code text not null unique default ('RET-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),order_reference text not null,customer_name text not null,phone text not null,product_name text not null,reason text not null,status text not null default 'requested' check(status in ('requested','approved','rejected','received','refunded','closed')),admin_note text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now()); grant insert on public.return_requests to anon,authenticated; grant select,update,delete on public.return_requests to authenticated; grant all on public.return_requests to service_role; alter table public.return_requests enable row level security; drop policy if exists "Anyone can request a return" on public.return_requests; create policy "Anyone can request a return" on public.return_requests for insert to anon,authenticated with check(length(trim(order_reference)) between 2 and 80 and length(trim(customer_name)) between 2 and 100 and length(regexp_replace(phone,'\D','','g')) between 10 and 15); drop policy if exists "Admins can view returns" on public.return_requests; create policy "Admins can view returns" on public.return_requests for select to authenticated using(private.is_admin()); drop policy if exists "Admins can update returns" on public.return_requests; create policy "Admins can update returns" on public.return_requests for update to authenticated using(private.is_admin()) with check(private.is_admin()); drop policy if exists "Admins can delete returns" on public.return_requests; create policy "Admins can delete returns" on public.return_requests for delete to authenticated using(private.is_admin());

create table if not exists public.notification_queue (id uuid primary key default gen_random_uuid(),kind text not null check(kind in('booking_created','booking_status','review_received','return_received')),recipient text not null,subject text not null,payload jsonb not null default '{}'::jsonb,status text not null default 'pending' check(status in('pending','sent','failed')),error_message text,created_at timestamptz not null default now(),sent_at timestamptz); grant select on public.notification_queue to authenticated; grant all on public.notification_queue to service_role; alter table public.notification_queue enable row level security; drop policy if exists "Admins view notification queue" on public.notification_queue; create policy "Admins view notification queue" on public.notification_queue for select to authenticated using(private.is_admin());

drop trigger if exists bookings_updated_at on public.bookings; create trigger bookings_updated_at before update on public.bookings for each row execute function public.set_updated_at(); drop trigger if exists reviews_updated_at on public.reviews; create trigger reviews_updated_at before update on public.reviews for each row execute function public.set_updated_at(); drop trigger if exists coupons_updated_at on public.coupons; create trigger coupons_updated_at before update on public.coupons for each row execute function public.set_updated_at(); drop trigger if exists return_requests_updated_at on public.return_requests; create trigger return_requests_updated_at before update on public.return_requests for each row execute function public.set_updated_at();

create or replace function public.validate_coupon(p_code text,p_amount numeric default 0) returns jsonb language plpgsql stable security definer set search_path='' as $$ declare c public.coupons; discount numeric:=0; begin select * into c from public.coupons where upper(code)=upper(trim(p_code)) and is_active=true and starts_at<=now() and (ends_at is null or ends_at>=now()) and (max_uses is null or used_count<max_uses) limit 1; if not found then return jsonb_build_object('valid',false,'message','Coupon is invalid or expired.'); end if; if p_amount<c.minimum_amount then return jsonb_build_object('valid',false,'message',format('Minimum amount is ₹%s.',c.minimum_amount)); end if; discount:=case when c.discount_type='percent' then round(p_amount*c.discount_value/100,2) else c.discount_value end; return jsonb_build_object('valid',true,'code',c.code,'discount',least(discount,p_amount),'description',c.description); end; $$; revoke all on function public.validate_coupon(text,numeric) from public; grant execute on function public.validate_coupon(text,numeric) to anon,authenticated; insert into public.coupons(code,description,discount_type,discount_value,minimum_amount) values('KAARAS500','15th Anniversary ₹500 OFF on eligible salon services','fixed',500,1500) on conflict(code) do nothing;
